travis:
  secure:
    BINSTAR_TOKEN: qDn1PlOvfRfxpczENJNgL6hnLR0BOzuojUZ7bdQg6vYCY8Zmz4HuiSI/B2a+eks8gwpRZWaT8ppo+Id4q24OiOuiRQ1vrzmpP1Uywc33W5BLTiPn38LuH6RBrl0Ee8242yAT7G7uzBde/kbV1rw2T65o0SI0BOzqGr78ooef4NOzVNzyn5GjPfIYNo+P+IG7vuXW+chLeQhXCNKUL+jGQl9+BkMGwhEn/G7c/zA/KproLUJK5zjq141Hk1i717M05/q7DXnlJqsxgTek07cYcsUjnPVV8huPbwEr8eE5lQQADujKiAE4ImWzUj4cHlTR+F7TgCYLpwHDL5ikzdpG5rJIF+TPdErqVJ+nOuzRNC3650G7XI96RZOaZU0X/wNsRmT++JSMgnWfWHvHkphXnTgc4X/HGZLXiZ/0vdWHKjKaoT6F4/2cIyvnW3bgPgBpevFg3XjAGZOP0o8sTTVeZFRYhRrPWMK6LPsHb9gAt7/TVT5w5fwnUQmkxDNU9ozHRuCCln1EqspICuvz0oHc8qu5V4Hni0ny6j3Hi41nLTKbx5ZKby4PtXPglbbwcZnzQJivAlO5m1zZWTkbXuevX64ATxs5QKZHwTKMeRajdK9apIa+YbESPyv62tn2epRW1G06H4Q1/FGFqQP+eLwQG7QClw4PR8ZM0pwt73ZXeEE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
